#!/usr/bin/env bash
# Generates the Homebrew formula for signls and pushes it to the emprcl/homebrew-tap
# repository. signls assembles its release manually across several runners (see
# .goreleaser.yaml), so goreleaser's own brews pipe can't run; this reproduces the
# formula it would have generated, using the sha256 sums from the combined
# checksums.txt once every platform's archive is published.
set -euo pipefail

VERSION="${VERSION#v}" # tag is vX.Y.Z; the formula wants X.Y.Z
DIST="${DIST:-dist}"

TAP_OWNER="emprcl"
TAP_REPO="homebrew-tap"
BASE_URL="https://github.com/emprcl/signls/releases/download/v${VERSION}"

# Look up the checksum of a given os_arch archive from the combined checksums.txt.
sha() {
  local file="signls_${VERSION}_$1.tar.gz"
  awk -v f="$file" '$2 == f { print $1 }' "${DIST}/checksums.txt"
}

darwin_amd64="$(sha darwin_amd64)"
darwin_arm64="$(sha darwin_arm64)"
linux_amd64="$(sha linux_amd64)"
linux_arm64="$(sha linux_arm64)"

for target in darwin_amd64 darwin_arm64 linux_amd64 linux_arm64; do
  if [ -z "${!target}" ]; then
    echo "missing checksum for ${target} in ${DIST}/checksums.txt" >&2
    exit 1
  fi
done

cat > signls.rb <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by signls's release workflow. DO NOT EDIT.
class Signls < Formula
  desc "Non-linear, generative MIDI sequencer for the terminal"
  homepage "https://empr.cl/signls/"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "${BASE_URL}/signls_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"

      define_method(:install) do
        bin.install "signls"
      end
    end
    if Hardware::CPU.arm?
      url "${BASE_URL}/signls_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"

      define_method(:install) do
        bin.install "signls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${BASE_URL}/signls_${VERSION}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
      define_method(:install) do
        bin.install "signls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${BASE_URL}/signls_${VERSION}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
      define_method(:install) do
        bin.install "signls"
      end
    end
  end

  test do
    system "#{bin}/signls", "--version"
  end
end
EOF

git clone --depth 1 \
  "https://x-access-token:${HOMEBREW_TAP_GITHUB_TOKEN}@github.com/${TAP_OWNER}/${TAP_REPO}.git" \
  tap

cp signls.rb tap/signls.rb

cd tap
git config user.name "goreleaserbot"
git config user.email "bot@goreleaser.com"

git add signls.rb
if git diff --cached --quiet; then
  echo "signls.rb already up to date for v${VERSION}; nothing to push."
  exit 0
fi

git commit -m "Brew formula update for signls version v${VERSION}"
git push
